-- Generated by tools/generate_data_modules.py. Edit data/, not this file.
if not Salve or not Salve.Sound or not Salve.Sound.RegisterData then return end

Salve.Sound:RegisterData("Salve_Data_Midnight_S2", {
    [1592] = {
        name = "Sporefall",
        season = "Midnight Season 2",
        seasonSource = "https://news.blizzard.com/en-us/article/24294369/the-shadows-deepen-midnight-season-2-begins-august-18",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 1221714,
                dispelType = "Poison",
                name = "Poison Burst",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [1762] = {
        name = "Kings' Rest",
        season = "Midnight Season 2",
        seasonSource = "https://news.blizzard.com/en-us/article/24294369/the-shadows-deepen-midnight-season-2-begins-august-18",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 267273,
                dispelType = "Poison",
                name = "Poison Nova",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 267763,
                dispelType = "Disease",
                name = "Wretched Discharge",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [1877] = {
        name = "Temple of Sethraliss",
        season = "Midnight Season 2",
        seasonSource = "https://news.blizzard.com/en-us/article/24294369/the-shadows-deepen-midnight-season-2-begins-august-18",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 267027,
                dispelType = "Poison",
                name = "Poison Spit",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [2521] = {
        name = "Ruby Life Pools",
        season = "Midnight Season 2",
        seasonSource = "https://news.blizzard.com/en-us/article/24294369/the-shadows-deepen-midnight-season-2-begins-august-18",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
        },
    },
    [2813] = {
        name = "Murder Row",
        season = "Midnight Season 2",
        seasonSource = "https://news.blizzard.com/en-us/article/24294369/the-shadows-deepen-midnight-season-2-begins-august-18",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 474515,
                dispelType = "Poison",
                name = "Heartstop Poison",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1228198,
                dispelType = "Magic",
                name = "Corroding Spittle",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [2825] = {
        name = "Den of Nalorakk",
        season = "Midnight Season 2",
        seasonSource = "https://news.blizzard.com/en-us/article/24294369/the-shadows-deepen-midnight-season-2-begins-august-18",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 1234846,
                dispelType = "Poison",
                name = "Toxic Spores",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [2859] = {
        name = "The Blinding Vale",
        season = "Midnight Season 2",
        seasonSource = "https://news.blizzard.com/en-us/article/24294369/the-shadows-deepen-midnight-season-2-begins-august-18",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 1236658,
                dispelType = "Magic",
                name = "Bloodthorn Roots",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [2923] = {
        name = "Voidscar Arena",
        season = "Midnight Season 2",
        seasonSource = "https://news.blizzard.com/en-us/article/24294369/the-shadows-deepen-midnight-season-2-begins-august-18",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 1226031,
                dispelType = "Poison",
                name = "Poison Splash",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1263971,
                dispelType = "Poison",
                name = "Mind-Numbing Poison",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [2987] = {
        name = "The Tidebound Grotto",
        season = "Midnight Season 2",
        seasonSource = "https://news.blizzard.com/en-us/article/24294369/the-shadows-deepen-midnight-season-2-begins-august-18",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
        },
    },
    [2993] = {
        name = "Altar of Fangs",
        season = "Midnight Season 2",
        seasonSource = "https://news.blizzard.com/en-us/article/24294369/the-shadows-deepen-midnight-season-2-begins-august-18",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 1296069,
                dispelType = "Disease",
                name = "Regurgitate",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [3004] = {
        name = "The Venomous Abyss",
        season = "Midnight Season 2",
        seasonSource = "https://news.blizzard.com/en-us/article/24294369/the-shadows-deepen-midnight-season-2-begins-august-18",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 1284471,
                dispelType = "Magic",
                name = "Blighted Blood",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1287036,
                dispelType = "Poison",
                name = "Poisonous Bite",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1295173,
                dispelType = "Magic",
                name = "Exploding Infection",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1301800,
                dispelType = "Poison",
                name = "Acidic Burst",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1305650,
                dispelType = "Magic",
                name = "Anguished Cry",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
})
