-- Generated by tools/generate_data_modules.py. Edit data/, not this file.
if not Salve then return end

if not Salve.Sound or not Salve.Sound.RegisterData then return end

Salve.Sound:RegisterData("Salve_Data_Midnight_S1", {
    [658] = {
        name = "Pit of Saron",
        season = "Midnight Season 1",
        seasonSource = "https://worldofwarcraft.blizzard.com/en-us/news/24244646",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 1261921,
                dispelType = "Magic",
                name = "Cryoshards",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1264186,
                dispelType = "Curse",
                name = "Shadowbind",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [1209] = {
        name = "Skyreach",
        season = "Midnight Season 1",
        seasonSource = "https://worldofwarcraft.blizzard.com/en-us/news/24244646",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
        },
    },
    [1753] = {
        name = "Seat of the Triumvirate",
        season = "Midnight Season 1",
        seasonSource = "https://worldofwarcraft.blizzard.com/en-us/news/24244646",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
        },
    },
    [2526] = {
        name = "Algeth'ar Academy",
        season = "Midnight Season 1",
        seasonSource = "https://worldofwarcraft.blizzard.com/en-us/news/24244646",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 389033,
                dispelType = "Poison",
                name = "Lasher Toxin",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [2805] = {
        name = "Windrunner Spire",
        season = "Midnight Season 1",
        seasonSource = "https://worldofwarcraft.blizzard.com/en-us/news/24244646",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
        },
    },
    [2811] = {
        name = "Magisters' Terrace",
        season = "Midnight Season 1",
        seasonSource = "https://worldofwarcraft.blizzard.com/en-us/news/24244646",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 1214038,
                dispelType = "Magic",
                name = "Ethereal Shackles",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1214714,
                dispelType = "Magic",
                name = "Void Torrent",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1248689,
                dispelType = "Magic",
                name = "Hastening Ward",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1284627,
                dispelType = "Magic",
                name = "Umbral Splinters",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [2874] = {
        name = "Maisara Caverns",
        season = "Midnight Season 1",
        seasonSource = "https://worldofwarcraft.blizzard.com/en-us/news/24244646",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 1246666,
                dispelType = "Disease",
                name = "Infected Pinions",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1254175,
                dispelType = "Magic",
                name = "Cries of the Fallen",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1260709,
                dispelType = "Magic",
                name = "Vilebranch Sting",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [2912] = {
        name = "The Voidspire",
        season = "Midnight Season 1",
        seasonSource = "https://worldofwarcraft.blizzard.com/en-us/news/24244646",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 1233865,
                dispelType = "Magic",
                name = "Null Corona",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1258514,
                dispelType = "Magic",
                name = "Blinding Light",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1259186,
                dispelType = "Magic",
                name = "Blisterburst",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1261531,
                dispelType = "Magic",
                name = "Corrupting Essence",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1272527,
                dispelType = "Magic",
                name = "Creep Spit",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1275059,
                dispelType = "Curse",
                name = "Black Miasma",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
    [2913] = {
        name = "March on Quel'Danas",
        season = "Midnight Season 1",
        seasonSource = "https://worldofwarcraft.blizzard.com/en-us/news/24244646",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
        },
    },
    [2915] = {
        name = "Nexus-Point Xenas",
        season = "Midnight Season 1",
        seasonSource = "https://worldofwarcraft.blizzard.com/en-us/news/24244646",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
        },
    },
    [2939] = {
        name = "The Dreamrift",
        season = "Midnight Season 1",
        seasonSource = "https://worldofwarcraft.blizzard.com/en-us/news/24244646",
        coverage = "Encounter Journal baseline; trash may be absent",
        debuffs = {
            {
                spellID = 1249017,
                dispelType = "Magic",
                name = "Fearsome Cry",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
            {
                spellID = 1257087,
                dispelType = "Magic",
                name = "Consuming Miasma",
                verified = true,
                provenance = {
                    source = "wago.tools DB2 JournalEncounterSection+SpellCategories",
                    build = "12.1.0.69299",
                },
            },
        },
    },
})
